### ISSUE TITLE
Configuration changes are reflected in live reload with delay

### ISSUE THREAD

**Issue by jelhan** [empress/empress-blog#114]
Changes to the configuration in `config/environment.js` are not picked up by live reload immediately after the change. But they are picked up by the next change.

This affects at least `title`, `description` and `navigation` configuration options. I have not tested with others.

It seems to be a caching issue. The cache seems to be updated _after_ the reload happens and therefore reflect the live reload cycle before.

## Steps to reproduce

1. Start development server.
2. Change the `blog.title` configuration option to `"foo"`.
3. Change the `blog.title` configuration option to `"bar"`.

## Actual behavior

Both changes of the configuration trigger a rebuild and reload of the application. After the first change the title seems to be unchanged. After the second change the title is shown as `"foo"`.

## Expected behavior

I would have expected to see the title `"foo"` after the first change and the title `"bar"` after the second change.

**Comment by mansona** [comment]
So, to be perfectly honest, I'm surprised that the the title even updated at all 😬 I was under the impression that configuration changes would require you to restart the server and this is something that was a known issue with ember-cli 🤔 

How much of an issue is this for you? This is only affecting local development and isn't causing any production issues for you is it?

**Comment by jelhan** [comment]
It is not critical for me. It don't think it can affect production as a fresh build is always up to date. It is only a little bit confusing when configuring a new blog. So it might not help with broader adoption. Therefore I thought it might be good to report.

I just double-checked with a new Ember application created with `ember-cli@3.25.3` _without_ installing Empress Blog and seeing the same issue. Seems to be an issue with Ember CLI and not with Empress Blog. Will try to find some time tomorrow to report upstream.

**Comment by mansona** [comment]
Thanks for double-checking that this was actually an ember-cli issue 👍 I'm going to close this now as it is a problem upstream
