### ISSUE TITLE
Title is included twice in post and page blueprints

### ISSUE THREAD

**Issue by jelhan** [empress/empress-blog#115]
Post and page blueprints contain the title twice: Once as a front-matter meta data and once as a first-level heading.

```md
---
title: <%= title %>
---

# Write Me
```

**Comment by elwayman02** [comment]
@jelhan I don't think that's actually a bug. The title that gets rendered at the top of an article comes from the front-matter meta data. After that, it's just a markdown file, and it's totally valid to use a `#` heading if you want to. It can also be deleted - you can format the markdown content however you wish!

For example, here's an article I wrote that uses both "titles", as you put it: https://helladrunk.com/welcome

As you can see, the front-matter title appears at the top of the page, and the markdown content is rendered below the image. I chose to keep the `#` header with a different text, but I could have removed it as well. It's not intended that you put the same text in both places.

**Comment by mansona** [comment]
While I 100% agree with @elwayman02 on this one, I have just removed it from the blueprint to avoid any confusion 👍

**Comment by jelhan** [comment]
Thanks a lot.

My main reasons to report this were:

1. The markdown linter which I use in VSCode reports it as an error.
2. I assumed that having two first-level headlines is an a11y problem. I researched a little bit and actually it might be okay. But I still feel that two sibling `<h1>` for the same content seems wrong. 🤷‍♂️

**Comment by mansona** [comment]
from an accessibility perspective it is even more stringent, there should only be exactly one `<h1>` on the page. 

> The markdown linter which I use in VSCode reports it as an error. 

Can you explain this a bit more? what is the error that it is giving you?

**Comment by jelhan** [comment]
> > The markdown linter which I use in VSCode reports it as an error.
> 
> Can you explain this a bit more? what is the error that it is giving you?

I'm getting the following linter error:

> MD025/single-title/single-h1: Multiple top-level headings in the same document markdownlint (MD025)

![markdown-lint-double-headline](https://user-images.githubusercontent.com/4965703/115245004-c7540900-a124-11eb-8598-0f0660316de0.png)

I'm using VSCode extension [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint).

I haven't tested but I'm very sure that it is fixed by #117.

**Comment by mansona** [comment]
I'm super surprised that it's warning you about this 🤔  how does it know that there is a `<h1>` being provided by the Ember template 😂  🙃 

Glad it's fixed now tho 👍

**Comment by jelhan** [comment]
> I'm super surprised that it's warning you about this thinking how does it know that there is a `<h1>` being provided by the Ember template joy upside_down_face

From the documentation for the failing rule:

> If YAML front matter is present and contains a title property (commonly used with blog posts), this rule treats that as a top level heading and will report a violation for any subsequent top-level headings.
>
> https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md025

:exploding_head:

**Comment by mansona** [comment]
omg that's pretty intense 😂  at least it's doing the right thing 🤷
