### ISSUE TITLE
How to install to a subdirectory?

### ISSUE THREAD

**Issue by buremba** [empress/empress-blog#12]
I updated the `rootURL` in `config/environment.js` but all the images are broken and I see errors in the console because it can't fetch the JSON data via AJAX from `/content/content.json?path=content` How can I install ember-ghost in a subdirectory?

**Comment by mansona** [comment]
@buremba installing this in a sub-directory is not currently supported (not using rootURL anyway) for the exact reasons you are describing.

Can you tell me more about your use-case and what you're trying to achieve with having it in a subdirectory and we can figure out if there is something that we can do to help you 😄

**Comment by buremba** [comment]
Hey @mansona , we wanted to install the blog under our company domain (https://rakam.io/blog) for SEO purposes. Now using Hugo since they have support for it. :/

**Comment by mansona** [comment]
@buremba I'm curious what you mean by "for SEO purposes" because blog.rakam.io and rakam.io/blog are exactly the same when it comes to SEO 🤔 

I can pull up the recent video of the Google SEO guy saying this if you would like 😄 

Also, you didn't quite answer my question. I wanted to know your use case so I could figure out how to help you. Is your main website (rakam.io) using Ember? i.e. would adding support for an Ember Engine work in your case?

**Comment by buremba** [comment]
rakam.io is a separate website built with Hugo. Even though Google claims that subdirectory & subdomain doesn't make any difference, the reality is a bit different unfortunately because we saw that rakam.io's other subpages started to get more attraction. 
The idea was that we would install empress-blog on a different subdomain and use forwarding rules to make it live on rakam.io/blog but since the project doesn't provide something like `siteUrl` that supports subdirectory, we couldn't use it.

**Comment by mansona** [comment]
ah great, so this is exactly why I was asking these questions 😄 if you are looking to deploy it using a subdomain where the rest of the site is a completely different technology (i.e. not also using Ember) then this is more of a hosting concern than an empress-blog concern 👍 

I'm happy to walk you through it and provide an example for you. First thing I need is more details on how you deploy, do you use S3 and CloudFront? or are you using a custom nginx server to serve your main website?
