### ISSUE TITLE
Add ember-responsive-image documentation

### ISSUE THREAD

**Issue by MichalBryxi** [empress/empress-blog#122]
I just updated empress-blog `3.0.1` to `3.2.0` and that gave me bump of `ember-responsive-image` from `1.0.1` to `2.0.0` and now during `start start` I'm getting:

```
WARNING: Could not find config for ember-responsive-image, skipping image processing...
```

Would be probably good to have a hint in README / documentation what to do or where to look to set this up?

Note: I guess even before that `ember-responsive-image` was not working for me either?

**Comment by MichalBryxi** [comment]
Hmm actually I'm not sure why did the `empress-responsive-image` update? The only mention I can find is in [pakcage.json](https://github.com/empress/empress-blog/blob/master/package.json#L84). I guess `empress-blog` is not prepared for `>= v3.2.0` of `ember-responsive-image` yet?

**Comment by MichalBryxi** [comment]
Heh seems like [at one point](https://github.com/empress/empress-blog/pull/119) I was aware that there will be incompatibility :)

**Comment by elwayman02** [comment]
@MichalBryxi the error is tracked here: https://github.com/empress/empress-blog-casper-template/issues/39 2.x of ember-responsive-image had breaking changes that need to be fixed in the Casper template.

**Comment by MichalBryxi** [comment]
Bumping to `v2.x` of `ember-responsive-image` would probably fix a lot of these problems. For sure. I think we can then close this issue and [this PR](https://github.com/empress/empress-blog/pull/119).
