### ISSUE TITLE
ember-responsive-image fails to find image metadata

### ISSUE THREAD

**Issue by elwayman02** [empress/empress-blog#140]
I created a brand-new Empress app to test: https://github.com/elwayman02/test-blog

Used the following commands:

```
npx ember-cli@3.27.0 new test-blog
cd test-blog
npx ember install empress-blog empress-blog-casper-template
npm start
```

The default blog doesn't render images properly:

![image](https://user-images.githubusercontent.com/1325482/132268003-64c53645-9cff-46cb-91f7-a05c5f5ee186.png)

> Error: Assertion Failed: There is no data for image images/welcome.jpg

The error is thrown from here: https://github.com/kaliber5/ember-responsive-image/blob/master/addon/services/responsive-image-local.ts#L52

The metadata in `images` does actually exist, but for some reason when we attempt to access the object `this.meta.images` with the key `images/welcome.jpg`, it comes back as undefined and fails the assertion.

**Comment by simonihmig** [comment]
@elwayman02 I was not able to reproduce this. I cloned your `test-blog` and started it, and images showed up correctly:

![image](https://user-images.githubusercontent.com/1325249/132320013-5c415d81-4b97-4d9b-aa54-275a4c3d2ebd.png)

Also in the console I see a bunch of deprecations, but no errors!? 🤔

I do see some weird glitches with Chrome (but not FF), that images disappear, mostly when scrolled out of view, and reappear again, e.g. on hover. But no errors in the console, and there isn't anything dynamic happening after initial rendering on behalf of `e-r-i`, so seems unrelated to me, maybe something related to the CSS effects, idk...

**Comment by simonihmig** [comment]
For the record: after chatting with @elwayman02 on Discord, another possible explanation came up related to problems downloading the libvips binaries that sharp needs. @mansona can you confirm you got such problems when installing? And what kind of machine are you using? Anything more "fancy" like those M1 Macs? 

I do know there were issues with those for example, but I believe the latest sharp should support those just fine now...

**Comment by simonihmig** [comment]
To add to this, trying to make some sense to the difficulties in reproducing this, when you folks are in front of a machine that "successfully" reproduces the problem, it would be good to know:
* are there any warnings or errors when installing the dependencies, especially related to sharp?
* what is the json content of the `<script id="ember_responsive_image_meta" type="application/json">`, that you should be able to see looking at the source of index.html
* when the assertion is thrown, is this happening during Fastboot rendering (i.e. exception visible in the terminal), or in the browser (dev console)?
* when you are able to see the assertion described above, can you put a breakpoint before it and see what the value of `this.meta` is [here](https://github.com/kaliber5/ember-responsive-image/blob/master/addon/services/responsive-image-local.ts#L52)?

**Comment by elwayman02** [comment]
This is likely a Windows-specific bug due to the mixed use of backslash and forward slash into the windows file system vs the browser. I've filed the following bug to track a fix: https://github.com/kaliber5/ember-responsive-image/issues/337

**Comment by elwayman02** [comment]
Fixed by https://github.com/empress/empress-blog-casper-template/pull/46 and https://github.com/kaliber5/ember-responsive-image/releases/tag/v3.1.1, will go out with the next release
