### ISSUE TITLE
Why use ember-data at all?

### ISSUE THREAD

**Issue by NullVoxPopuli** [empress/empress-blog#186]
since blogs are statically generated and maybe with optional runtime bits for component demos, why do we need to use ember-data?

(nothing against ember-data here, just seems like a weird choice for a static site?)

**Comment by mansona** [comment]
ember-data works well for caching purposes 👍

**Comment by NullVoxPopuli** [comment]
what cache does empress rely on that browser native cache would not work for?
How often is fetching happening?

**Comment by mansona** [comment]
having a deep cache of the authors is quite useful 👍

**Comment by NullVoxPopuli** [comment]
what do you mean? how so? why not ship it all without the abstraction of needing to be fetched? author data isn't that big is it?
