### ISSUE TITLE
`Site Not Found`: empress-blog.netlify.com

### ISSUE THREAD

**Issue by johanrd** [empress/empress-blog#187]
1. Click the about url from the repo home page (https://empress-blog.netlify.com/)
2. Experience `Site Not Found` error on Netlify:
<img width="967" alt="Screenshot 2024-08-05 at 11 41 08" src="https://github.com/user-attachments/assets/8abe38e2-7d06-4bdc-8859-3ad089b551e2">

**Comment by mansona** [comment]
ah sorry, netlify changed the `.com` suffix with `.app` a while back. I guess they stopped redirecting now 😞

**Comment by mansona** [comment]
I've updated the link in the description now to https://empress-blog.netlify.app/ 👍
