### ISSUE TITLE
how do I use a multi-line description?

### ISSUE THREAD

**Issue by NullVoxPopuli** [empress/empress-blog#19]
currently, I have:
```
      description: `
        null: a keyword indicating that something has no value.\n
        vox populi: the voice of the people
      `,
```
and I've tried `<br>`, but I think the text is escaped?
(also, I tried an array of lines)

Is there anyway to indicate that I want multiple lines?

**Comment by mansona** [comment]
@NullVoxPopuli are multiple lines supported in Search Engines? 🤔 It's my understanding that Google will always flatten your description no matter what we do in the output. If I'm wrong then I'm happy to investigate the pipeline of addons that we're using and where the right place to enable this is 😂 👍

**Comment by NullVoxPopuli** [comment]
that's a good point. I guess since this is intended to be the search engine description, does it make sense to separate it from the blog subtext? 
I think it'd be goofy to have secret hidden text only available to search engines.
