### ISSUE TITLE
Navigation to Page

### ISSUE THREAD

**Issue by devotox** [empress/empress-blog#36]
When we navigate to page/ and refresh on netlify we get a 404 because page/ is not statically built.

Can we statically build it?

**Comment by devotox** [comment]
The way I've fixed this but means it is not SEO compatible is to add this to netlify _redirects
```
/page/* /_empty.html 200
```

**Comment by dfreeman** [comment]
@devotox You can supplement the URLs that Empress provides to `prember` by adding config like this to your `ember-cli-build.js`:

```js
  new EmberApp(defaults, {
    // ...
    prember: {
      urls: [
        ...require('fs')
          .readdirSync('page')
          .map(file => `/page/${file.replace(/\.md$/, '')}`)
      ]
    }
  });
```

But it probably makes sense for Empress to do this automatically, since it already does for e.g. `tags`?

**Comment by devotox** [comment]
If you give me some directions of where to look I could raise a PR @dfreeman

**Comment by dfreeman** [comment]
@devotox It looks like they're generating the URLs here: https://github.com/empress/empress-blog/blob/ec92c9103869c1189d38b091848eaace8fc0cd13/index.js#L209-L240

You could probably copy what it does to generate `authorURLs` and do the same for everything under `page` (which is essentially what the snippet I pasted above does, too)

**Comment by devotox** [comment]
@dfreeman thanks for the direction. PR created
