### ISSUE TITLE
Create your own theme

### ISSUE THREAD

**Issue by ishu3101** [empress/empress-blog#4]
How do you create your own theme to work with ember ghost? Is there a guide for this?

**Comment by mansona** [comment]
So there is not currently a guide 🤔 my current process for creating themes is to convert Ghost themes to be Ember Ghost themes but I wasn't really expecting to have to write a guide for Ember Ghost only themes for quite some time 😂 

Are you looking to do something entirely custom? Or do you have a ghost theme that you would like to convert?

**Comment by ishu3101** [comment]
I would like to convert an existing ghost theme to an ember ghost theme. But even knowing how to create an entirely custom one from scratch would also be useful.

**Comment by mansona** [comment]
I think the best way to proceed would be to convert another theme and then while doing that we can document the process and some of the tools that are available to us in the templating side of this.

Is the theme open source? do you have a link to it?

**Comment by ishu3101** [comment]
I have just being using the ember ghost casper template so far but having a documentation would be very useful

**Comment by mansona** [comment]
So what I was proposing was that we work together to convert your theme and document as we go 😄 I often think that it's best to have a real-world example that we can aim towards when doing initial documentation 👍 

Are you able to jot down some documentation if you're already in the process of porting your theme?

**Comment by ishu3101** [comment]
Currently I am trying to get my blog up and running with github pages before I start making changes to the theme.

**Comment by ishu3101** [comment]
How does ember-ghost determine which theme to use?

**Comment by mansona** [comment]
Hey @ishu3101 👋 Sorry I didn't see your question in July, Ember-Ghost templates are just installed via npm and the template you have in the package.json is the one that will be used 👍 

If you follow the [instructions on the quick start](https://github.com/empress/ember-ghost#quick-start) it will install 2 dependencies for you, the base addon `ember-ghost` and the `ember-ghost-casper-template`

**Comment by mansona** [comment]
As for writing your own template, I'm starting the process to make it **significantly** easier for people to work on their own templates. I have just released [create-ember-ghost-template](https://github.com/empress/create-ember-ghost-template) which allows you to start your own template using the following command: 

```sh
npm init ember-ghost-template <name-of-your-template>
```

You can check out the documentation on that repo and let me know if it's good enough to get started 👍

**Comment by mansona** [comment]
@ishu3101 did you try out the template initialisation step?

**Comment by nickschot** [comment]
@mansona Just fyi I'm gonna go through this soon as I integrate empres-blog into my personal site.

**Comment by mansona** [comment]
I am now confident that the template generation is good enough to be considered stable 👍 

If anyone has any issues with it then please open another issue 😄
