### ISSUE TITLE
ember-lodash adds significant weight to production builds

### ISSUE THREAD

**Issue by dfreeman** [empress/empress-blog#51]
I've noticed that `empress-blog` relies on `ember-lodash` to include the full `lodash` package in the build, but it's only actually making use of a few utilities.

Since this package already has dependencies on `ember-auto-import` and `lodash` directly, it should be possible to drop `ember-lodash` and rewrite the existing imports not to pull in the entire package, e.g. `import pick from 'lodash/pick';`.

Making that change locally knocked about 68K (nearly a quarter) off my gzipped production `vendor.js` size.

| | Raw Size | Gzipped Size |
|-|----------|--------------|
|Before| 1.27 MB | 313.44 KB |
|After | 947.58 KB | 245.62 KB |
|Difference| **-323 KB** | **-67.82 KB** |

If you'd be open to the change, I'm happy to open a PR. One wrinkle is that `empress-blog-casper-template` seems to be implicitly relying on `import _ from 'lodash'` working without ever declaring a dependency that would enable that. I'm not using that template myself, but since this package's own dummy app is, a similar change would need to happen there first.

**Comment by nickschot** [comment]
I'd like this to happen as well! Seems like the easiest optimalization to slim it down.

**Comment by nickschot** [comment]
As a small update, I started working on implementing this by moving default template helpers into https://github.com/empress/empress-blog-ghost-helpers which will use the optimized imports. The template addons will be updated to include this addon. Apart from that we'll need to optimize the excerpt helper present in empress-blog itself (which also uses lodash).
