### ISSUE TITLE
Install fails on Node 12

### ISSUE THREAD

**Issue by Ry7n** [empress/empress-blog#59]
Following the quickstart guide, I get the error:

```
installing empress-blog-casper-template
  install addon ember-responsive-image
Command failed: npm install --save-dev --loglevel error ember-responsive-image
info sharp Using cached /Users/ryan/.npm/_libvips/libvips-8.7.0-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=12.16.2 runtime=node arch=x64 libc= platform=darwin)
In file included from ../src/common.cc:27:
../src/common.h:78:20: error: no member named 'Handle' in namespace 'v8'
  bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
               ~~~~^
../src/common.h:78:37: error: expected '(' for function-style cast or type construction
  bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                          ~~~~~~~~~~^
../src/common.h:78:39: error: use of undeclared identifier 'obj'
  bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                      ^
../src/common.h:78:56: error: expected '(' for function-style cast or type construction
  bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
````

It's not the fault of this module, but rather an issue with a transitive dependency on an old version of sharp (see https://github.com/kaliber5/ember-responsive-image/issues/51).

The solution recommended in the linked issue resolves it here as well, but you need to use [yarn](https://yarnpkg.com/).

After doing `npm init` add the following to `package.json`:

```json
  "resolutions": {
    "**/sharp": "^0.25.2"
  },
```

Then:

```sh
yarn import && rm package-lock.json
```

After that, `npx ember-cli install empress-blog empress-blog-casper-template` will work just fine.

Since presumably `ember-responsive-image` will fix its sharp dependency eventually, it may not be worth changing anything, but this issue might help someone else scratching their head when the quick start fails them.

**Comment by mansona** [comment]
Hey @Ry7n I'm pretty sure this has been fixed. I got the change merged upstream in ember-responsive-image and updated all the dependencies down the chain. 

In my tests this is now working fine 🎉  I'm going to close this now and let me know if you still have the issue 👍
