### ISSUE TITLE
Code Highlighting Not Working

### ISSUE THREAD

**Issue by jrock2004** [empress/empress-blog#75]
So I just created locally a new blog and trying to do some code formatting and all I am getting is a black box with white text. Am I doing something wrong or is that how its suppose to be?

![image](https://user-images.githubusercontent.com/655716/91249632-3c517900-e725-11ea-868e-92b7863579a6.png)

Here is what I wrote in the markdown

```js
import Model, { attr } from '@ember-data/model';

export default class PostModel extends Model {
  @attr title;
  @attr body;
}
```

**Comment by mansona** [comment]
that is currently what is expected by default, but you can also install https://github.com/empress/ember-showdown-prism and it will start automatically adding more code highlighting 👍 

Let me know if that works

**Comment by jrock2004** [comment]
Yes, that worked. Thanks
